version: '3'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/App:/usr/src
    ports:
      - 4000:4000
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src
    ports:
      - 3000:3000